# =============================================================================
# FILE: .github/workflows/main.yml
# Main CI/CD Pipeline Entrypoint
# =============================================================================
name: RigoHR Workhorse CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TZ: Asia/Kathmandu
  VAULT_ADDR: https://openbao.app.rigohr.com
  AWS_REGION: ap-south-1

jobs:
  # Job 1: Fetch secrets from Vault and make them available
  fetch_secrets:
    uses: ./.github/workflows/fetch-vault-secret.yml
    permissions:
      id-token: write
      contents: read

  # Job 2: Tag the release
  tag:
    needs: fetch_secrets
    uses: ./.github/workflows/tag.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ needs.fetch_secrets.outputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ needs.fetch_secrets.outputs.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ needs.fetch_secrets.outputs.AWS_DEFAULT_REGION }}
      