# .github/workflows/main.yml
name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-test1:
    uses: ./.github/workflows/test1.yml

  call-test2:
    needs: call-test1
    uses: ./.github/workflows/test2.yml
    with:
      my_var: ${{ needs.call-test1.outputs.my_var }}
