name: Main Orchestration Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1. Call test1.yml to compute and get the variable
  get_variable_job:
    uses: ./.github/workflows/test1.yml

  # 2. Call test2.yml and pass the variable received in step 1
  pass_variable_job:
    needs: get_variable_job
    uses: ./.github/workflows/test2.yml
    with:
      shared_variable: ${{ needs.get_variable_job.outputs.my_var }}
