# .github/workflows/test1.yml
name: Test 1

on:
  workflow_call:
    outputs:
      my_var:
        description: "Variable from test1"
        value: ${{ jobs.create_var.outputs.my_var }}

jobs:
  create_var:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.setvar.outputs.my_var }}
    steps:
      - name: Set variable
        id: setvar
        run: echo "my_var=Hello from Test1" >> $GITHUB_OUTPUT
