name: Test 1 - Compute Variable

on:
  workflow_call:
    outputs:
      my_variable_output:
        description: "The variable computed in Test 1"
        value: ${{ jobs.set_output.outputs.computed_value }}

jobs:
  set_output:
    runs-on: ubuntu-latest
    outputs:
      computed_value: ${{ steps.set_var.outputs.result }}
    steps:
      - name: Compute and Set Variable
        id: set_var
        run: |
          MY_VAR="hello-from-test1-$(date +%Y%m%d)"
          echo "Computed variable: $MY_VAR"
          echo "result=$MY_VAR" >> $GITHUB_OUTPUT
